apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: tfjob
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: tensorflow
            image: repository/dlrs-tensorflow-kf:v0.7.0 
            workingDir: /opt/tf-benchmarks/scripts/tf_cnn_benchmarks
            command:
              - python
              - tf_cnn_benchmarks.py
              - --batch_size=32
              - --model=alexnet
              - --variable_update=parameter_server
              - --local_parameter_device=cpu
              - --init_learning_rate=0.0001
              - --tf_random_seed=8286
              - --device=cpu
              - --data_format=NHWC
    Worker:
      replicas: 3
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: tensorflow
            image: repository/dlrs-kf-mkl:v0.5.0
            workingDir: /opt/tf-benchmarks/scripts/tf_cnn_benchmarks
            command:
              - python
              - tf_cnn_benchmarks.py
              - --batch_size=32
              - --model=alexnet
              - --variable_update=parameter_server
              - --local_parameter_device=cpu
              - --init_learning_rate=0.0001
              - --tf_random_seed=8286
              - --device=cpu
              - --data_format=NHWC
    Master:
          replicas: 1
          restartPolicy: Never
          template:
            spec:
              containers:
              - name: tensorflow
                image: repository/dlrs-tensorflow-kf:v0.7.0
                workingDir: /opt/tf-benchmarks/scripts/tf_cnn_benchmarks
                command:
                  - python
                  - tf_cnn_benchmarks.py
                  - --batch_size=32
                  - --model=alexnet
                  - --variable_update=parameter_server
                  - --local_parameter_device=cpu
                  - --init_learning_rate=0.0001
                  - --tf_random_seed=8286
                  - --device=cpu
                  - --data_format=NHWC
