apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-job-cnn-benchmark"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: pytorch
              image: repository/dlrs-pytorch-kf:v0.7.0
    Worker:
      replicas: 1
      restartPolicy: Never 
      template:
        spec:
          containers: 
            - name: pytorch
              image: repository/dlrs-pytorch-kf:v0.9.0
