apiVersion: v1
kind: Service
metadata:
  {{- $serviceName := printf "%s-cassandra" .Release.Name  }}
  name: {{ $serviceName }}
  labels:
    {{- $appLabel := printf "%s-cassandra" .Release.Name  }}      
    app: {{ $appLabel }}
spec:
  ports:
  - port: 9042
    name: cql
  clusterIP: None
  selector:
    app: {{ $appLabel }}
