apiVersion: "v1"
kind: "Pod"
metadata:
  name: "ghissue-inference"
  namespace: kubeflow 
spec:
  containers:
    - name: inference
      image: <your-registry>/stacks-dlrs-mkl-inference:v0.4.1
      volumeMounts:
        - mountPath: "/workdir"
          name: "preprocess-workdir"
  restartPolicy: Never
  volumes:
    - name: "preprocess-workdir"
      persistentVolumeClaim:
        claimName: "tfevent-pvc"
