version: "3.5"
services:
  main_controller:
    container_name: ic-main-controller
    image: ic-main-controller
    build:
      context: ./services/main_controller
      dockerfile: ./Dockerfile
    networks:
      icnet:
        ipv4_address: 172.25.0.3
    environment:
      - API_PORT=8000
    ports:
      - "${BACKEND_PORT:-8000}:8000"
  effects_service:
    container_name: ic-effects-service
    image: ic-effects-service
    build:
      context: ./services/effects_service
      dockerfile: ./Dockerfile
    networks:
      icnet:
        ipv4_address: 172.25.0.4
    environment:
      - API_PORT=8000
    volumes:
      - ${MODELS_DIR:-./saved_models}:/workspace/src/effects_service/models
  video_proxy:
    container_name: ic-video-proxy
    image: ic-video-proxy
    build:
      context: ./services/video_proxy
      dockerfile: ./Dockerfile
    networks:
      icnet:
        ipv4_address: 172.25.0.5
    privileged: true
    cap_add:
      - ALL
    environment:
      - API_PORT=8000
      - ZMQ_IP=172.25.0.4
    volumes:
      - /dev/:/dev
  device_manager:
    container_name: ic-device-manager
    image: ic-device-manager
    build:
      context: ./services/device_manager
      dockerfile: ./Dockerfile
    networks:
      icnet:
        ipv4_address: 172.25.0.6
    environment:
      - API_PORT=8000
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /lib/modules:/lib/modules
      - /dev/:/dev:ro
  ui_controller:
    container_name: ic-ui-controller
    image: ic-ui-controller
    build:
      context: ./services/ui_controller
      dockerfile: ./Dockerfile
    networks:
      icnet:
        ipv4_address: 172.25.0.7
    ports:
      - "${UI_PORT:-8080}:80"
    environment:
      - REACT_APP_MAIN_CONTROLLER_API=http://172.25.0.3:8000

networks:
  icnet:
    name: icnet
    driver: bridge
    ipam:
        config:
            - subnet: 172.25.0.0/16
